### PR TITLE
C++11: Use override instead of virtual.

### PR DESCRIPTION
**Pull request by ya1gaurav**
Use override in case of destructor also.

### CODE REVIEW

**Comment by murraycu** [comment]
Sorry. We don't use github pull requests for glibmm. Could you please put this in bugzilla?

**Comment by murraycu** [comment]
I would close this as a duplicate of your other pull requests if I could:
https://github.com/GNOME/glibmm/pull/2

Please use bugzilla next time.

**Comment by murraycu** [comment]
@aruiz , Do you know how I can close unwanted gnome mirror github pull requests?

**Comment by aruiz** [comment]
Only admins can close them. I can close this one if you want.

**Comment by murraycu** [comment]
Yes, please, and the duplicate.

**Pull request closed without merging**
